services:
  postgres:
    image: postgres:latest
    container_name: easy-cloud-snack
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=easy-cloud-snack
    ports:
      - "5432:5432"
